<br />
<h3>Allow users to:</h3>
<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditGlobalAttributes() ? 'checked' : '' ?>
           name="allowupdateglobalattrs"
           id="allowupdateglobalattrs"
           value="1" />&nbsp;
    <label for="allowupdateglobalattrs"><?php echo $this->__('Update global attributes') ?></label>
</div>
<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditOwnProductsOnly() ? 'checked' : '' ?>
           name="caneditownproductsonly"
           id="caneditownproductsonly"
           value="1" />&nbsp;
    <label for="caneditownproductsonly"><?php echo $this->__('Management of only products owned by user') ?></label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->manageOrdersOwnProductsOnly() ? 'checked' : '' ?>
           name="manage_orders_own_products_only"
           id="manage_orders_own_products_only"
           value="1" />&nbsp;
    <label for="manage_orders_own_products_only">
        <b><?php echo $this->__('Allow manage orders with own products only') ?></b>
    </label>
</div>


<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddStoreViews() ? 'checked' : '' ?>
           name="canaddstoreviews"
           id="canaddstoreviews"
           value="1" />&nbsp;
    <label for="canaddstoreviews"><?php echo $this->__('Management of store views under assigned websites') ?></label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditStoreViews() ? 'checked' : '' ?>
           name="caneditstoreviews"
           id="caneditstoreviews"
           value="1" />&nbsp;
    <label for="caneditstoreviews"><?php echo $this->__('Editing of store views under assigned websites.') ?><b> <?php echo $this->__('Note: Limits are the user can not delete or add') ?></b></label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddStoreGroups() ? 'checked' : '' ?>
           name="canaddstoregroups"
           id="canaddstoregroups"
           value="1" />&nbsp;
    <label for="canaddstoregroups"><?php echo $this->__('Management of store groups under assigned websites.') ?></label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditStoreGroups() ? 'checked' : '' ?>
           name="caneditstoregroups"
           id="caneditstoregroups"
           value="1" />&nbsp;
    <label for="caneditstoregroups"><?php echo $this->__('Editing of store groups under assigned websites.') ?> <b> <?php echo $this->__(' Note: Limits are the user can not delete or add') ?></b></label>
</div>


<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddWebSites() ? 'checked' : '' ?>
           name="canaddwebsites"
           id="canaddwebsites"
           value="1" />&nbsp;
    <label for="canaddwebsites"><?php echo $this->__('Management of any Website.') ?></label>
</div>


<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditWebSites() ? 'checked' : '' ?>
           name="caneditwebsites"
           id="caneditwebsites"
           value="1" />&nbsp;
    <label for="caneditwebsites"><?php echo $this->__('Editing of assigned Website.') ?> <b> <?php echo $this->__(' Note: Limits are the user can not delete or add') ?></b></label>
</div>

