<br />

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditGlobalAttributes() ? 'checked="checked"' : '' ?>
           name="allowupdateglobalattrs"
           id="allowupdateglobalattrs"
           value="1" />&nbsp;
    <label for="allowupdateglobalattrs">
        <b><?php echo $this->__('Allow update global attributes') ?></b>
    </label>
</div>

<br />

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditOwnProductsOnly() ? 'checked="checked"' : '' ?>
           name="caneditownproductsonly"
           id="caneditownproductsonly"
           value="1" />&nbsp;
    <label for="caneditownproductsonly">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddStoreViews() ? 'checked="checked"' : '' ?>
           name="canaddstoreviews"
           id="canaddstoreviews"
           value="1" />&nbsp;
    <label for="canaddstoreviews">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditStoreViews() ? 'checked="checked"' : '' ?>
           name="caneditstoreviews"
           id="caneditstoreviews"
           value="1" />&nbsp;
    <label for="caneditstoreviews">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddStoreGroups() ? 'checked="checked"' : '' ?>
           name="canaddstoregroups"
           id="canaddstoregroups"
           value="1" />&nbsp;
    <label for="canaddstoregroups">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditStoreGroups() ? 'checked="checked"' : '' ?>
           name="caneditstoregroups"
           id="caneditstoregroups"
           value="1" />&nbsp;
    <label for="caneditstoregroups">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>


<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canAddWebSites() ? 'checked="checked"' : '' ?>
           name="canaddwebsites"
           id="canaddwebsites"
           value="1" />&nbsp;
    <label for="canaddwebsites">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>



